# Install my VSCode extensions
code --install-extension astro-build.astro-vscode
code --install-extension GitHub.vscode-codeql
code --install-extension golang.go
code --install-extension GraphQL.vscode-graphql
code --install-extension bruno-api-client.bruno
code --install-extension jasonnutter.vscode-codeowners
code --install-extension mikestead.dotenv
code --install-extension EditorConfig.EditorConfig
code --install-extension usernamehw.errorlens
code --install-extension dbaeumer.vscode-eslint
code --install-extension github.vscode-github-actions
code --install-extension GitHub.vscode-pull-request-github
code --install-extension JanBiasi.gotthard-theme
code --install-extension wix.vscode-import-cost
code --install-extension vscode-icons-team.vscode-icons
code --install-extension PKief.material-icon-theme
code --install-extension esbenp.prettier-vscode
code --install-extension yoavbls.pretty-ts-errors
code --install-extension Gruntfuggly.todo-tree
code --install-extension redhat.vscode-yaml
code --install-extension formulahendry.auto-close-tag
code --install-extension BazelBuild.vscode-bazel
code --install-extension adpyke.codesnap
code --install-extension vscjava.vscode-java-pack
code --install-extension antfu.file-nesting
code --install-extension donjayamanne.githistory
code --install-extension naco-siren.gradle-language
code --install-extension lokalise.i18n-ally
code --install-extension wayou.vscode-todo-highlight
