blacklist = ["scratch", "temp", ".nix-profile", ".ssh", "Library"]

sort_order = [
  "tmuxinator", # show first
  "config",
  "tmux",
  "zoxide",     # show last
]

[path_substitutions]
[[find_and_replace]]
find = "~/.local/share/git"
replace = "git:"

[[window]]
name = "git"
startup_script = "git pull"

[[window]]
name = "neovim"
startup_script = "nvim ."

[[window]]
name = "shell"

[default_session]
# startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "Obsidian 🧠"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Second Brain"
startup_command = "nvim ."
preview_command = "ls -la"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "hosts"
path = "/etc/hosts"
startup_command = "nvim /etc/hosts"
preview_command = "bat --color=always /etc/hosts"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
preview_command = "bat --color=always README.md"
windows = ["neovim"]

[[session]]
name = "seekme"
path = "~/.local/share/git/seekmeio/"
windows = ["api", "platform", "website"]
