blacklist = ["scratch", "temp"]

[default_session]
# startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "Obsidian 🧠"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Second Brain"
startup_command = "nvim ."
preview_command = "ls -la"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "hosts"
path = "/etc/hosts"
startup_command = "nvim /etc/hosts"
preview_command = "bat --color=always /etc/hosts"
