general {
    lock_cmd = sh -c 'pidof hyprlock >/dev/null || { hyprlock; brightnessctl -r; }'
    inhibit_sleep = 3
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = 90
    on-timeout = sh -c 'pidof hyprlock >/dev/null || { hyprlock; brightnessctl -r; }'
}

listener {
    timeout = 120
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

# TODO: Find a hardware-generic way to detect the power state.
listener {
    timeout = 300
    condition_cmd = grep -qx 0 /sys/class/power_supply/ACAD/online
    condition_retry = 5
    on-timeout = systemctl suspend
}

listener {
    timeout = 1800
    condition_cmd = grep -qx 1 /sys/class/power_supply/ACAD/online
    condition_retry = 5
    on-timeout = systemctl suspend
}
