- name: Setup global NPM configuration
  copy:
    dest: ~/.npmrc
    src: ~/{{ repo.name }}/ansible/roles/node/files/.npmrc

- name: Installing node version manager {{ node.nvm.version }} (NVM)
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ node.nvm.version }}/install.sh | bash
  tags: nvm

- name: Setup global NVM configuration
  copy:
    dest: ~/.nvmrc
    src: ~/{{ repo.name }}/ansible/roles/node/files/.nvmrc

- name: Installing node version {{ node.version }}
  shell: source ~/.nvm/nvm.sh && nvm install {{ node.version }}
  tags: nvm
  args:
    executable: /bin/bash
