- name: Setup global git config
  tags: git
  copy:
    dest: ~/.gitconfig
    src: ~/{{ repo.name }}/.config/git/.gitconfig

- name: Setup global gitignore
  tags: git
  copy:
    dest: ~/.gitignore
    src: ~/{{ repo.name }}/.config/git/.gitignore

- name: Use keychain for SSH
  tags: git
  copy:
    dest: ~/.ssh/
    src: ~/{{ repo.name }}/.config/git/ssh/
