#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
THEME_DIR="$CONFIG_DIR/themes"

# Load selected theme colors
source "$THEME_DIR/catppuccin.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=32        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font=":$FONT_WEIGHT:$FONT_SIZE"  \
                     icon.color=$WHITE                 \
                     label.font="$FONT:$FONT_WEIGHT:$FONT_SIZE" \
                     label.color=$WHITE                \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=5            \
                     background.height=22                  \
                     background.border_width=1 \
                     background.border_color=$BLACK_2 \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=8                \
                     icon.padding_left=8                  \
                     icon.padding_right=4

# # -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# # -- Right Side Items --
source $ITEM_DIR/clock.sh
source $ITEM_DIR/keyboard.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/ip_address.sh
source $ITEM_DIR/cpu.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
