# Generated by Matugen. Source this file from the Hyprpolkit launcher.
export HPA_PRIMARY='{{colors.primary.default.hex}}'
export HPA_ON_PRIMARY='{{colors.on_primary.default.hex}}'
export HPA_SECONDARY='{{colors.secondary.default.hex}}'
export HPA_BACKGROUND='{{colors.surface.default.hex}}'
export HPA_SURFACE_HIGH='{{colors.surface_container_high.default.hex}}'
export HPA_FOREGROUND='{{colors.on_surface.default.hex}}'
