local palettes = {
  dark = {
    bg = '{{colors.surface.dark.hex}}',
    fg = '{{colors.on_surface.dark.hex}}',
    muted = '{{colors.on_surface_variant.dark.hex}}',
    primary = '{{colors.primary.dark.hex}}',
    on_primary = '{{colors.on_primary.dark.hex}}',
    primary_container = '{{colors.primary_container.dark.hex}}',
    on_primary_container = '{{colors.on_primary_container.dark.hex}}',
    secondary_container = '{{colors.secondary_container.dark.hex}}',
    tertiary_container = '{{colors.tertiary_container.dark.hex}}',
    surface = '{{colors.surface.dark.hex}}',
    surface_low = '{{colors.surface_container_low.dark.hex}}',
    surface_lowest = '{{colors.surface_container_lowest.dark.hex}}',
    surface_container = '{{colors.surface_container.dark.hex}}',
    surface_high = '{{colors.surface_container_high.dark.hex}}',
    outline = '{{colors.outline.dark.hex}}',
    outline_variant = '{{colors.outline_variant.dark.hex}}',
    error = '{{colors.error.dark.hex}}',
    warning = '{{colors.tertiary_fixed_dim.dark.hex}}',
    created = '{{colors.success.dark.hex | to_color | set_hue: 140 | set_saturation: 55.0 | set_lightness: 68.0}}',
    modified = '{{colors.tertiary.dark.hex | to_color | set_hue: 42 | set_saturation: 65.0 | set_lightness: 68.0}}',
    renamed = '{{colors.primary.dark.hex | to_color | set_hue: 210 | set_saturation: 55.0 | set_lightness: 68.0}}',
    keyword = '{{colors.syntax_keyword.dark.hex | to_color | set_saturation: 65.0 | set_lightness: 68.0}}',
    type = '{{colors.syntax_type.dark.hex | to_color | set_saturation: 65.0 | set_lightness: 68.0}}',
    string = '{{colors.success.dark.hex | to_color | set_saturation: 55.0 | set_lightness: 68.0}}',
    func = '{{colors.primary.dark.hex | to_color | set_saturation: 60.0 | set_lightness: 68.0}}',
    number = '{{colors.tertiary.dark.hex | to_color | set_saturation: 60.0 | set_lightness: 68.0}}',
    special = '{{colors.error.dark.hex | to_color | set_saturation: 60.0 | set_lightness: 68.0}}',
    terminal = {
      '{{colors.surface_dim.dark.hex}}',
      '{{colors.error.dark.hex}}',
      '{{colors.tertiary.dark.hex}}',
      '{{colors.tertiary_fixed_dim.dark.hex}}',
      '{{colors.primary.dark.hex}}',
      '{{colors.secondary.dark.hex}}',
      '{{colors.primary_fixed_dim.dark.hex}}',
      '{{colors.on_surface.dark.hex}}',
      '{{colors.surface_container_high.dark.hex}}',
      '{{colors.error.dark.hex}}',
      '{{colors.tertiary.dark.hex}}',
      '{{colors.tertiary_fixed.dark.hex}}',
      '{{colors.primary.dark.hex}}',
      '{{colors.secondary.dark.hex}}',
      '{{colors.primary_fixed.dark.hex}}',
      '{{colors.on_surface.dark.hex}}',
    },
  },
  light = {
    bg = '{{colors.surface_container_lowest.light.hex}}',
    fg = '{{colors.on_surface.light.hex}}',
    muted = '{{colors.on_surface_variant.light.hex}}',
    primary = '{{colors.primary.light.hex}}',
    on_primary = '{{colors.on_primary.light.hex}}',
    primary_container = '{{colors.primary_container.light.hex}}',
    on_primary_container = '{{colors.on_primary_container.light.hex}}',
    secondary_container = '{{colors.secondary_container.light.hex}}',
    tertiary_container = '{{colors.tertiary_container.light.hex}}',
    surface = '{{colors.surface.light.hex}}',
    surface_low = '{{colors.surface_container_low.light.hex}}',
    surface_lowest = '{{colors.surface_container_lowest.light.hex}}',
    surface_container = '{{colors.surface_container.light.hex}}',
    surface_high = '{{colors.surface_container_high.light.hex}}',
    outline = '{{colors.outline.light.hex}}',
    outline_variant = '{{colors.outline_variant.light.hex}}',
    error = '{{colors.error.light.hex}}',
    warning = '{{colors.tertiary_fixed_dim.light.hex}}',
    created = '{{colors.success.light.hex | to_color | set_hue: 140 | set_saturation: 65.0 | set_lightness: 32.0}}',
    modified = '{{colors.tertiary.light.hex | to_color | set_hue: 42 | set_saturation: 70.0 | set_lightness: 34.0}}',
    renamed = '{{colors.primary.light.hex | to_color | set_hue: 210 | set_saturation: 65.0 | set_lightness: 38.0}}',
    keyword = '{{colors.syntax_keyword.light.hex | to_color | set_saturation: 65.0 | set_lightness: 38.0}}',
    type = '{{colors.syntax_type.light.hex | to_color | set_saturation: 65.0 | set_lightness: 38.0}}',
    string = '{{colors.success.light.hex | to_color | set_saturation: 55.0 | set_lightness: 36.0}}',
    func = '{{colors.primary.light.hex | to_color | set_saturation: 60.0 | set_lightness: 38.0}}',
    number = '{{colors.tertiary.light.hex | to_color | set_saturation: 60.0 | set_lightness: 38.0}}',
    special = '{{colors.error.light.hex | to_color | set_saturation: 60.0 | set_lightness: 38.0}}',
    terminal = {
      '{{colors.surface_dim.light.hex}}',
      '{{colors.error.light.hex}}',
      '{{colors.tertiary.light.hex}}',
      '{{colors.tertiary_fixed_dim.light.hex}}',
      '{{colors.primary.light.hex}}',
      '{{colors.secondary.light.hex}}',
      '{{colors.primary_fixed_dim.light.hex}}',
      '{{colors.on_surface.light.hex}}',
      '{{colors.surface_container_high.light.hex}}',
      '{{colors.error.light.hex}}',
      '{{colors.tertiary.light.hex}}',
      '{{colors.tertiary_fixed.light.hex}}',
      '{{colors.primary.light.hex}}',
      '{{colors.secondary.light.hex}}',
      '{{colors.primary_fixed.light.hex}}',
      '{{colors.on_surface.light.hex}}',
    },
  },
}
local c = palettes[vim.o.background]

local function blend(fg, bg, opacity)
  local rgb = {}
  for i = 1, 3 do
    local offset = i * 2
    local front = tonumber(fg:sub(offset, offset + 1), 16)
    local back = tonumber(bg:sub(offset, offset + 1), 16)
    rgb[i] = math.floor(front * opacity + back * (1 - opacity) + 0.5)
  end
  return string.format('#%02x%02x%02x', unpack(rgb))
end

vim.cmd 'highlight clear'
if vim.g.syntax_on then vim.cmd 'syntax reset' end
vim.o.termguicolors = true
vim.g.colors_name = 'matugen'

local cursorline = blend(c.surface_container, c.bg, 0.5)
local comment = blend(c.muted, c.bg, vim.o.background == 'dark' and 0.5 or 0.7)
local highlights = {
  Normal = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = c.surface_high },
  FloatBorder = { fg = c.outline_variant, bg = c.surface_high },
  FloatTitle = { fg = c.primary, bg = c.surface_high, bold = true },
  Cursor = { fg = c.on_primary, bg = c.primary },
  CursorLine = { bg = cursorline },
  CursorLineNr = { fg = c.primary, bold = true },
  LineNr = { fg = blend(c.muted, c.bg, vim.o.background == 'dark' and 0.6 or 1) },
  SignColumn = { bg = c.bg },
  WinSeparator = { fg = c.outline_variant },
  ColorColumn = { bg = blend(c.outline_variant, c.bg, 0.25) },
  StatusLine = { fg = c.fg, bg = c.surface },
  StatusLineNC = { fg = c.muted, bg = c.surface_lowest },
  TabLine = { fg = c.muted, bg = c.surface },
  TabLineFill = { bg = c.surface },
  TabLineSel = { fg = c.fg, bg = c.surface_container },
  Pmenu = { fg = c.fg, bg = c.surface_high },
  PmenuSel = { fg = c.on_primary_container, bg = c.primary_container },
  PmenuMatch = { fg = c.primary, bold = true },
  PmenuMatchSel = { fg = c.on_primary_container, bg = c.primary_container, bold = true },
  PmenuSbar = { bg = c.surface_container },
  PmenuThumb = { bg = c.outline },
  Visual = { bg = blend(c.secondary_container, c.bg, 0.5) },
  Search = { fg = c.fg, bg = blend(c.tertiary_container, c.bg, 0.5) },
  IncSearch = { fg = c.on_primary, bg = c.primary },
  MatchParen = { fg = c.primary, bg = c.primary_container, bold = true },
  NonText = { fg = blend(c.outline_variant, c.bg, 0.5) },
  Folded = { fg = c.muted, bg = c.surface_container },
  FoldColumn = { fg = c.muted, bg = c.bg },
  Directory = { fg = c.primary },
  Title = { fg = c.primary, bold = true },
  MoreMsg = { fg = c.created },
  Question = { fg = c.primary },
  ErrorMsg = { fg = c.error },
  WarningMsg = { fg = c.warning },
  DiffAdd = { bg = blend(c.created, c.bg, 0.16) },
  DiffChange = { bg = blend(c.modified, c.bg, 0.16) },
  DiffDelete = { fg = c.error, bg = blend(c.error, c.bg, 0.16) },
  DiffText = { bg = blend(c.renamed, c.bg, 0.25) },
  Comment = { fg = comment },
  Constant = { fg = c.func },
  String = { fg = c.string },
  Number = { fg = c.number },
  Identifier = { fg = c.fg },
  Function = { fg = c.func },
  Statement = { fg = c.keyword },
  Operator = { fg = c.muted },
  Type = { fg = c.type },
  Special = { fg = c.special },
  Delimiter = { fg = c.muted },
  Error = { fg = c.error },
  Todo = { fg = c.on_primary, bg = c.primary, bold = true },
  Underlined = { fg = c.primary, underline = true },
  Conceal = { fg = c.muted },
  LspReferenceText = { bg = blend(c.primary_container, c.bg, 0.375) },
  LspReferenceWrite = { bg = blend(c.secondary_container, c.bg, 0.5) },
  LspSignatureActiveParameter = { fg = c.primary, bold = true },
  GitSignsAdd = { fg = c.created },
  GitSignsChange = { fg = c.modified },
  GitSignsDelete = { fg = c.error },
  TelescopeSelection = { fg = c.fg, bg = cursorline },
  TelescopeMatching = { fg = c.primary, bold = true },
  BlinkCmpLabel = { fg = c.fg },
  BlinkCmpLabelMatch = { fg = c.primary, bold = true },
  BlinkCmpLabelDescription = { fg = c.muted },
  BlinkCmpGhostText = { fg = comment },
  NeoTreeNormal = { fg = c.fg, bg = c.surface_low },
  NeoTreeCursorLine = { bg = c.surface_container },
  NeoTreeRootName = { fg = c.primary, bold = true },
  NeoTreeFileNameOpened = { fg = c.fg, bold = true },
  NeoTreeGitRenamed = { fg = c.renamed },
  NeoTreeTitleBar = { fg = c.on_primary_container, bg = c.primary_container },
  MiniStatuslineModeNormal = { fg = c.on_primary, bg = c.primary, bold = true },
  MiniStatuslineModeInsert = { fg = c.bg, bg = c.created, bold = true },
  MiniStatuslineModeVisual = { fg = c.bg, bg = c.type, bold = true },
  MiniStatuslineModeReplace = { fg = c.bg, bg = c.error, bold = true },
  MiniStatuslineModeCommand = { fg = c.bg, bg = c.warning, bold = true },
  MiniStatuslineDevinfo = { fg = c.fg, bg = c.surface_container },
  MiniStatuslineFilename = { fg = c.fg, bg = c.surface },
  MiniStatuslineFileinfo = { fg = c.fg, bg = c.surface_container },
}
for name, definition in pairs(highlights) do
  vim.api.nvim_set_hl(0, name, definition)
end

for severity, color in pairs { Error = c.error, Warn = c.warning, Info = c.primary, Hint = c.primary, Ok = c.created } do
  vim.api.nvim_set_hl(0, 'Diagnostic' .. severity, { fg = color })
  vim.api.nvim_set_hl(0, 'DiagnosticSign' .. severity, { fg = color, bg = c.bg })
  vim.api.nvim_set_hl(0, 'DiagnosticVirtualText' .. severity, { fg = color, bg = blend(color, c.bg, 0.1) })
  vim.api.nvim_set_hl(0, 'DiagnosticUnderline' .. severity, { sp = color, undercurl = true })
end

local links = {
  NormalNC = 'Normal',
  FloatFooter = 'FloatTitle',
  TermCursor = 'Cursor',
  CursorColumn = 'CursorLine',
  CurSearch = 'IncSearch',
  Whitespace = 'NonText',
  EndOfBuffer = 'NonText',
  Boolean = 'Number',
  Float = 'Number',
  Character = 'String',
  Conditional = 'Statement',
  Repeat = 'Statement',
  Label = 'Statement',
  Keyword = 'Statement',
  Exception = 'Statement',
  PreProc = 'Statement',
  Include = 'Statement',
  Define = 'Statement',
  Macro = 'Statement',
  PreCondit = 'Statement',
  StorageClass = 'Type',
  Structure = 'Type',
  Typedef = 'Type',
  SpecialChar = 'Constant',
  SpecialComment = 'Comment',
  Debug = 'Special',
  LspReferenceRead = 'LspReferenceText',
  GitSignsCurrentLineBlame = 'Comment',
  ['@comment'] = 'Comment',
  ['@constant'] = 'Constant',
  ['@constant.builtin'] = 'Constant',
  ['@string'] = 'String',
  ['@string.escape'] = 'Constant',
  ['@string.regexp'] = 'Constant',
  ['@string.special'] = 'Constant',
  ['@string.special.symbol'] = 'Number',
  ['@character'] = 'String',
  ['@number'] = 'Number',
  ['@boolean'] = 'Boolean',
  ['@float'] = 'Float',
  ['@variable'] = 'Identifier',
  ['@variable.builtin'] = 'Special',
  ['@variable.parameter'] = 'Identifier',
  ['@variable.member'] = 'Identifier',
  ['@function'] = 'Function',
  ['@function.builtin'] = 'Function',
  ['@function.call'] = 'Function',
  ['@function.macro'] = 'Function',
  ['@function.method'] = 'Function',
  ['@constructor'] = 'Type',
  ['@keyword'] = 'Keyword',
  ['@operator'] = 'Operator',
  ['@type'] = 'Type',
  ['@type.builtin'] = 'Type',
  ['@property'] = 'Identifier',
  ['@attribute'] = 'Type',
  ['@module'] = 'Type',
  ['@punctuation.bracket'] = 'Delimiter',
  ['@punctuation.delimiter'] = 'Delimiter',
  ['@punctuation.special'] = 'Special',
  ['@tag'] = 'Special',
  ['@tag.attribute'] = 'Identifier',
  ['@tag.delimiter'] = 'Delimiter',
  ['@markup.raw'] = 'String',
  ['@markup.heading'] = 'Title',
  ['@markup.link'] = 'Underlined',
  ['@markup.list'] = 'Number',
  ['@lsp.type.class'] = 'Type',
  ['@lsp.type.enum'] = 'Type',
  ['@lsp.type.enumMember'] = 'Constant',
  ['@lsp.type.function'] = 'Function',
  ['@lsp.type.interface'] = 'Type',
  ['@lsp.type.keyword'] = 'Keyword',
  ['@lsp.type.method'] = 'Function',
  ['@lsp.type.namespace'] = 'Type',
  ['@lsp.type.parameter'] = 'Identifier',
  ['@lsp.type.property'] = 'Identifier',
  ['@lsp.type.struct'] = 'Type',
  ['@lsp.type.type'] = 'Type',
  ['@lsp.type.typeParameter'] = 'Type',
  ['@lsp.type.variable'] = 'Identifier',
  TelescopeNormal = 'NormalFloat',
  TelescopeBorder = 'FloatBorder',
  TelescopePromptNormal = 'NormalFloat',
  TelescopePromptBorder = 'FloatBorder',
  TelescopePromptPrefix = 'Function',
  TelescopePromptTitle = 'FloatTitle',
  TelescopeResultsTitle = 'FloatTitle',
  TelescopePreviewTitle = 'FloatTitle',
  BlinkCmpMenu = 'Pmenu',
  BlinkCmpMenuBorder = 'FloatBorder',
  BlinkCmpMenuSelection = 'PmenuSel',
  BlinkCmpDoc = 'NormalFloat',
  BlinkCmpDocBorder = 'FloatBorder',
  BlinkCmpSignatureHelp = 'NormalFloat',
  BlinkCmpSignatureHelpBorder = 'FloatBorder',
  NeoTreeNormalNC = 'NeoTreeNormal',
  NeoTreeSignColumn = 'NeoTreeNormal',
  NeoTreeDirectoryName = 'Directory',
  NeoTreeDirectoryIcon = 'Directory',
  NeoTreeFileName = 'Identifier',
  NeoTreeFileIcon = 'Identifier',
  NeoTreeSymbolicLinkTarget = 'Underlined',
  NeoTreeIndentMarker = 'NonText',
  NeoTreeExpander = 'Comment',
  NeoTreeDotfile = 'Comment',
  NeoTreeHiddenByName = 'Comment',
  NeoTreeWindowsHidden = 'Comment',
  NeoTreeDimText = 'Comment',
  NeoTreeMessage = 'Comment',
  NeoTreeFadeText1 = 'Comment',
  NeoTreeFadeText2 = 'Comment',
  NeoTreeFileStats = 'Comment',
  NeoTreeFileStatsHeader = 'Comment',
  NeoTreeModified = 'GitSignsChange',
  NeoTreeGitAdded = 'GitSignsAdd',
  NeoTreeGitDeleted = 'GitSignsDelete',
  NeoTreeGitModified = 'GitSignsChange',
  NeoTreeGitUntracked = 'GitSignsAdd',
  NeoTreeGitStaged = 'GitSignsAdd',
  NeoTreeGitUnstaged = 'GitSignsChange',
  NeoTreeGitConflict = 'DiagnosticError',
  NeoTreeGitIgnored = 'Comment',
  NeoTreeIgnored = 'Comment',
  NeoTreeSelected = 'Question',
  NeoTreeFilterTerm = 'Function',
  NeoTreeWinSeparator = 'WinSeparator',
  NeoTreeVertSplit = 'WinSeparator',
  NeoTreeEndOfBuffer = 'NonText',
  NeoTreeStatusLine = 'StatusLine',
  NeoTreeStatusLineNC = 'StatusLineNC',
  NeoTreeFloatNormal = 'NormalFloat',
  NeoTreeFloatBorder = 'FloatBorder',
  NeoTreeFloatTitle = 'FloatTitle',
  NeoTreeTabActive = 'TabLineSel',
  NeoTreeTabInactive = 'TabLine',
  NeoTreeTabSeparatorActive = 'WinSeparator',
  NeoTreeTabSeparatorInactive = 'WinSeparator',
  NeoTreePreview = 'Search',
  MiniStatuslineModeOther = 'MiniStatuslineModeNormal',
  MiniStatuslineInactive = 'StatusLineNC',
}
for name, target in pairs(links) do
  vim.api.nvim_set_hl(0, name, { link = target })
end

vim.api.nvim_set_hl(0, 'SpellBad', { sp = c.error, undercurl = true })
vim.api.nvim_set_hl(0, 'SpellCap', { sp = c.warning, undercurl = true })
vim.api.nvim_set_hl(0, 'SpellRare', { sp = c.primary, undercurl = true })
vim.api.nvim_set_hl(0, 'SpellLocal', { sp = c.primary, undercurl = true })
vim.api.nvim_set_hl(0, '@markup.italic', { italic = true })
vim.api.nvim_set_hl(0, '@markup.strong', { bold = true })
vim.api.nvim_set_hl(0, '@markup.strikethrough', { strikethrough = true })

for index, color in ipairs(c.terminal) do
  vim.g['terminal_color_' .. (index - 1)] = color
end
