"$schema" = 'https://starship.rs/config-schema.json'

# https://starship.rs/config/#prompt
format = """$shell$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
$character"""

# Put time on the right side
# https://starship.rs/config/#prompt
right_format = '''$time$battery'''

# format = """
# [░▒▓](surface1)\
# [  ](bg:surface2 fg:text)\
# [](bg:maroon fg:text)\
# $directory\
# [](fg:surface1 bg:#394260)\
# $git_branch\
# $git_status\
# [](fg:#394260 bg:#212736)\
# $nodejs\
# $rust\
# $golang\
# $php\
# [](fg:#212736 bg:#1d2230)\
# $time\
# [ ](fg:#1d2230)\
# \n$character"""

# Use catpuccin theme
palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = true

# --------------------------------------
# ------ Statusline configuration ------
# --------------------------------------

[character]
success_symbol = "[](bold fg:green)"
error_symbol = "[](bold fg:red)"
vimcmd_symbol = "[](bold fg:creen)"
vimcmd_replace_one_symbol = "[](bold fg:purple)"
vimcmd_replace_symbol = "[](bold fg:purple)"
vimcmd_visual_symbol = "[](bold fg:lavender)"

[os]
disabled = false

[os.symbols]
Macos = " 󰀵 "

[shell]
format = '[$indicator]($style)'
style = "surface1"
disabled = false

[[battery.display]]
threshold = 10
style = 'red'

[[battery.display]]
threshold = 30
style = 'yellow'


# [username]
# show_always = true
# format = '[ $user ]($style)'

[time]
disabled = false
time_format = "%R"                            # Hour:Minute Format
style = "fg:yellow"
format = '[[  $time ](fg:surface1)]($style)'

[directory]
format = "[ $path ]($style)"
style = "bold mauve"
truncation_symbol = "…/"
truncation_length = 3

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"node_modules" = ""
".github" = ""

[git_branch]
symbol = ""
#truncation_length = 24
format = "$symbol[[ $branch(:$remote_branch)](fg:sky)]($style) "

[git_status]
deleted = "✖"
# format = "[($all_status$ahead_behind )]($style)"

[cmd_duration]
format = "[$duration]($style)"

# -----------------------------------
# ------ Language integrations ------
# -----------------------------------

[package]
format = '[$version](fg:white) '

[nodejs]
symbol = ""
format = '| [[$symbol ($version)](fg:green)]($style) '

[golang]
symbol = ""
format = '| [[$symbol ($version)](fg:sky)]($style) '

[java]
symbol = ""
format = '| [[$symbol ($version)](bold bright-red)]($style) '

[bun]
symbol = ""

[kotlin]
symbol = ""

[scala]
symbol = ""

[rust]
symbol = ""
format = '| [[$symbol ($version)](fg:red)]($style) '

[gradle]
symbol = ""
format = '| [[$symbol ($version)](fg:yellow)]($style) '

[docker_context]
disabled = true

# ----------------------------
# ------ Color Palettes ------
# ----------------------------

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
