"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Put time on the right side
# https://starship.rs/config/#prompt
# right_format = '''$time$battery'''

# Starship modules

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](gray)"   # For use with zsh-vi-mode

[username]
disabled = true

[sudo]
disabled = false
style = "bold red"
symbol = "󰢏 root"
format = "[$symbol]($style)"

[directory]
truncation_length = 4
style = "yellow"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"node_modules" = ""
".github" = ""

[battery]
disabled = true

[[battery.display]]
threshold = 10
style = 'red'

[[battery.display]]
threshold = 30
style = 'yellow'

[time]
disabled = true
time_format = "%R"                         # Hour:Minute Format
style = "fg:yellow"
format = '[[   $time ](fg:gray)]($style)'

[package]
disabled = true

# Languages and indicator styles

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_status]
style = "purple"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "purple"

[docker_context]
disabled = true

[java]
symbol = "󰅶 "
version_format = "${major}"
style = "red"

[nodejs]
symbol = " "
version_format = "${major}"
style = "green"

[golang]
symbol = " "
version_format = "${major}.${minor}"
style = "blue"

[elixir]
symbol = " "
version_format = "${major}.${minor}"
style = "violet"

[erlang]
symbol = "  "
version_format = "${major}"
style = "pink"

[gradle]
symbol = " "
version_format = "${major}"
style = "blue"

[kotlin]
symbol = " "
version_format = "${major}"
style = "violet"

[scala]
symbol = " "
style = "orange"

[rust]
symbol = " "
style = "red"

[bun]
symbol = " "
style = "pink"

[nix_shell]
impure_msg = 'impure'
pure_msg = 'pure'
unknown_msg = 'unknown'
format = 'in [󱄅 nix](cyan)'

[cmd_duration]
min_time = 3500
format = "[ 󰅐 $duration]($style)"
style = "yellow"
