"$schema" = 'https://starship.rs/config-schema.json'

[package]
disabled = true

[java]
format = 'via [☕ $version](bold bright-red) '

[directory]
style = "purple"

[git_branch]
style = "cyan"

[git_state]
style = "yellow"